-- MySQL Script generated by MySQL Workbench
-- 10/31/16 02:35:03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test` DEFAULT CHARACTER SET utf8 ;
USE `test` ;

-- -----------------------------------------------------
-- Table `test`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`users` (
  `login` INT NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `passed` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test`.`IDSubject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`IDSubject` (
  `IDSubject` INT NOT NULL,
  `Subject` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDSubject`),
  CONSTRAINT `IDSubject`
    FOREIGN KEY ()
    REFERENCES `test`.`questions` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`questions` (
  `IDQuestion` INT NOT NULL,
  `Question` VARCHAR(100) NOT NULL,
  `IdRightAnswer` VARCHAR(100) NOT NULL,
  `IDSubject` INT NOT NULL,
  `TestID` INT NOT NULL,
  PRIMARY KEY (`IDSubject`),
  CONSTRAINT `IDSubject`
    FOREIGN KEY (`IDSubject`)
    REFERENCES `test`.`IDSubject` (`IDSubject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test`.`Answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`Answers` (
  `IDAnswer` INT NOT NULL,
  `Answer` VARCHAR(45) NOT NULL,
  `IDQuestion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDQuestion`),
  CONSTRAINT `IdRightAnswer`
    FOREIGN KEY ()
    REFERENCES `test`.`questions` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
